#=================================================
# Copyright (c) 2019-2023 sky2016cn
# Author: sky2016cn
# licensed under the MIT License
# See /LICENSE for more information
# Description: Build OpenWrt using GitHub Actions
#=================================================

name: Build_ax6000_LEDE_110m

# Add a button to trigger the workflow
on: 
  repository_dispatch:
  workflow_dispatch:

  #schedule:
    # UTC 时间对应北京时间（UTC+8=北京时间）：7月20日，早上5点10分 开始编译
    #- cron: '10 21 19 7 *'  
    # UTC 时间对应北京时间：每月2、9、16、23日，早上5点10分 开始编译    
    #- cron: '10 21 1,8,15,22 * *'
    
jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 2048
        temp-reserve-mb: 512
        swap-size-mb: 2048
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'
        overprovision-lvm: 'true'
        build-mount-path: '/builder'        

    - name: Prepare Builder Directory
      run: |
        sudo mkdir -p /builder
        sudo chown -R runner:runner /builder
        df -hT

    - name: Checkout repository
      uses: actions/checkout@v7        

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        # 1. 编译前，必须更新安装依赖包命令，请到 sky2016cn/OpenWrt-Depends 仓库：https://github.com/sky2016cn/OpenWrt-Depends/actions/workflows/update_dependency_LEDE.yml，运行一次"Run workflow"
        curl -fsSL https://raw.githubusercontent.com/sky2016cn/OpenWrt-Depends/main/depends-lede | sudo bash
                
        # 2. 清理系统无用软件包，释放磁盘空间
        echo "=== 正在清理临时文件和无用缓存 ==="
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo rm -rf /etc/apt/sources.list.d/* /usr/local/lib/android /opt/ghc /usr/share/dotnet /usr/local/graalvm /usr/local/.ghcup \
        /usr/local/share/powershell /usr/local/share/chromium /usr/local/lib/node_modules
        
        # 3. 设置时区并修正工作区权限
        sudo timedatectl set-timezone "Asia/Shanghai"
        sudo chown $USER:$GROUPS $GITHUB_WORKSPACE
        echo "✅ 环境初始化完毕！"

    - name: Check Space
      run: |
        df -h
        
    - name: Clone source code
      env: 
        REPO_URL: https://github.com/coolsnowwolf/lede
      run: |
        git clone --depth 1 -b master $REPO_URL /builder/openwrt || { echo 'Git clone failed!'; exit 1; }
        
        # ======== 编译下方插件，请先去掉注释 ======== 
        #cd /builder/openwrt

        # ======== 切换 luci 仓库：openwrt-23.05去掉注释，注释掉 openwrt-25.12 =========
        #sed -i 's|^#\(src-git luci .*openwrt-23\.05\)|\1|' ./feeds.conf.default
        #sed -i 's|^\(src-git luci .*openwrt-25\.12\)|#\1|' ./feeds.conf.default
        
        # ======== 编译 helloworld =========
        #echo "src-git helloworld https://github.com/fw876/helloworld.git" >> ./feeds.conf.default

        # ======== 编译 OpenClash 最新版 =========
        # Lede插件库已经包含 OpenClash，若源码被删除或编译 OpenClash 最新版，使用以下命令自行编译，打开Lede官方插件库查询：https://github.com/coolsnowwolf/lede/blob/master/feeds.conf.default（注意 luci后面的分支，打开 luci仓库中正确的分支找到“applications”查询插件）
        #sed -i '1i src-git openclash https://github.com/vernesong/OpenClash.git;master' ./feeds.conf.default
        
        # ======== 编译 Passwall 最新版 =========
        # Lede插件库已经包含 Passwall，若源码被删除或编译 Passwall 最新版，使用以下命令自行编译，打开Lede官方插件库查询：https://github.com/coolsnowwolf/lede/blob/master/feeds.conf.default（注意 luci后面的分支，打开 luci仓库中正确的分支找到“applications”查询插件）   
        # 编译 passwall_luci，去掉下面注释，此命令会在 feeds.conf.default文件，第 1 行插入 passwall_luci
        #sed -i '1i src-git passwall_luci https://github.com/Openwrt-Passwall/openwrt-passwall.git;main' ./feeds.conf.default

        # 编译 passwall_packages，再次在 feeds.conf.default文件，第 1 行插入 passwall_packages (这样 packages 就变成了第 1 行，luci 变成了第 2 行)
        #sed -i '1i src-git passwall_packages https://github.com/Openwrt-Passwall/openwrt-passwall-packages.git;main' ./feeds.conf.default
        
        # ======== 编译 Passwall2 最新版 =========
        # 编译 passwall2_luci，不要和 passwall_luci 一起编译，编译出来的固件会不稳定，第 1 行插入 passwall2_luci    
        #sed -i '1i src-git passwall2_luci https://github.com/Openwrt-Passwall/openwrt-passwall2.git;main' ./feeds.conf.default
               
    - name: Update feeds
      working-directory: /builder/openwrt
      run: |
        ./scripts/feeds update -a     

    - name: Install feeds
      working-directory: /builder/openwrt
      run: |
        ./scripts/feeds install -a

    - name: Install feeds
      working-directory: /builder/openwrt
      run: |
        ./scripts/feeds install -a

       # ======== 编译 OpenClash 最新版（使用 package 编译法）不推荐 =========
       # OpenClash 推荐使用上方写入 ./feeds.conf.default 编译法
       # Lede插件库已经包含 OpenClash，若源码被删除或编译 OpenClash 最新版，使用以下命令自行编译，打开Lede官方插件库查询：https://github.com/coolsnowwolf/lede/blob/master/feeds.conf.default（注意 luci后面的分支，打开 luci仓库中正确的分支找到“applications”查询插件）       
    #- name: Import Official Recommended OpenClash
    #  working-directory: /builder/openwrt
    #  run: |
        # 移除 openwrt feeds 自带的核心库，
    #    rm -rf package/luci-app-openclash
    #    rm -rf feeds/luci/applications/luci-app-openclash

        # 克隆 OpenClash 最新版
    #    git clone --depth=1 https://github.com/vernesong/OpenClash.git /tmp/OpenClash

    #    # 只移动 luci-app-openclash 软件包到 package 目录下
    #    mv /tmp/OpenClash/luci-app-openclash package/

        # 删除临时目录
    #    rm -rf /tmp/OpenClash
        
    # 范例 1: 添加源码中没有的第三方插件，必须放在 feeds命令之后，注意拉取命令的保存路径，打开Lede官方插件库查询：https://github.com/coolsnowwolf/lede/blob/master/feeds.conf.default（打开luci仓库找到“applications”查询插件）
    #- name: Import external feeds - OpenAppFilter
    #  working-directory: /builder/openwrt
    #  run: |
    #    git clone https://github.com/destan19/OpenAppFilter.git package/OpenAppFilter

    - name: Configuration Customization - Build_ax6000_LEDE_110m
      env:
        CONFIG_FILE: 'ax6000_LEDE_110m.config'
      run: |
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE /builder/openwrt/.config
        chmod +x ./customize.sh && ./customize.sh
        cd /builder/openwrt && make defconfig
        
    - name: Download package
      working-directory: /builder/openwrt
      run: |
        make download -j$(nproc)
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: Build firmware
      working-directory: /builder/openwrt
      run: |
        echo -e "$(nproc) thread build."
        # 先尝试多线程全速编译，如果失败（返回非 0 状态码），则触发单线程编译，并打印最详细的 V=s 日志
        make -j$(nproc) || make -j1 V=s

    - name: Check Space
      run: |
        df -h
        
    - name: Upload artifact
      uses: actions/upload-artifact@v7
      with:
        name: ax6000_LEDE_110m
        path: /builder/openwrt/bin
